# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build Markdown Exports

on:
  # Runs on an event fired by a Door43 webhook
  repository_dispatch:
    types: [build-obs-tf-web]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Transform mardown for exports and jekyll transformations
  preprocess-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.2/pandoc-3.1.2-1-amd64.deb
          sudo dpkg -i pandoc-3.1.2-1-amd64.deb
          pandoc -v
      - name: Fetch Markdown Files
        run: |
          sudo git clone https://git.door43.org/unfoldingWord/en_obs_tf.git ./obs
          ls
      - name: Convert To Pdf
        run: |
          pandoc -v
          pandoc --defaults ./obs/exportScripts/defaults/export.docx.yaml --lua-filter=./obs/exportScripts/lua-filters/obs.filter.docx.lua --reference-doc=./obs/exportScripts/reference-docs/obs_style_template.docx ./obs/obs_story_1.md -o obs_story_1.docx
          ls
